SisteMatriculacion/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'home/', include(('home.urls', 'home'), namespace ='home')),
    path(r'usuarios/', include(('usuarios.urls', 'usuarios'), namespace ='usuarios')),
    path(r'institucion/', include(('institucion.urls', 'institucion'), namespace ='institucion')),
    path(r'matricula/', include(('matricula.urls', 'matricula'), namespace ='matricula')),
    path(r'', include('home.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from home import views
# from django.contrib.auth import logout



urlpatterns = [
    # The home page
    path(r'', views.login, name='login'),
    path(r'index', views.index, name='index'),
    path(r'login', views.login, name='login'),
    url(r'logout', views.logout_view, name='logout'),
    # path(r'catalogo', views.catalogo, name='catalogo'),
    # path(r'nosotros', views.nosotros, name='nosotros'),
    # path(r'contacto', views.contacto, name='contacto'),
]

matricula/urls.py
from django.urls import path, include
from django.conf.urls import url
from matricula import views
# from django.contrib.auth import logout



urlpatterns = [
    # Matricula_estudiante
    path(r'matricula_create', views.matricula_create, name='matricula_create'),
    path(r'matricula_edit/<int:pk>/', views.matricula_edit, name='matricula_edit'),
    path(r'matricula_detail/<int:pk>/', views.MatriculaDetail.as_view(), name = 'matricula_detail'),
    path(r'matricula_list/', views.MatriculaList.as_view(), name = 'matricula_list'),

    # Matricula secretaria
    path(r'matriculas_pendientes_list/', views.matriculas_pendientes_list, name = 'matriculas_pendientes_list'),
    path(r'matriculados_list/', views.matriculados_list, name = 'matriculados_list'),
    path(r'matricula_aprobacion/<int:pk>/', views.matricula_aprobacion, name = 'matricula_aprobacion'),
    path(r'desaprobar_matricula/<int:pk>/', views.desaprobar_matricula, name = 'desaprobar_matricula'),
    path(r'certificado_matricula/<int:pk>/', views.certificado_matricula, name = 'certificado_matricula'),
    path(r'matricula_delete/<int:pk>/', views.MatriculaDelete.as_view(), name = 'matricula_delete'),

    # Lista de Estudiantes
    path(r'form_estudiantes_filter/', views.form_estudiantes_filter, name = 'form_estudiantes_filter'),
    # Solicitud de ingreso
    path(r'solicitud_ingreso_create/', views.solicitud_ingreso_create, name = 'solicitud_ingreso_create'),
    path(r'solicitud_ingreso/', views.solicitud_ingreso, name = 'solicitud_ingreso'),
    path(r'solicitud_ingreso_list/', views.solicitud_ingreso_list, name = 'solicitud_ingreso_list'),
    path(r'solicitudes_pendientes_list/', views.solicitudes_pendientes_list, name = 'solicitudes_pendientes_list'),
    path(r'solicitudes_aprobadas_list/', views.solicitudes_aprobadas_list, name = 'solicitudes_aprobadas_list'),
    path(r'aprobar_solicitud/<int:pk>/', views.aprobar_solicitud, name = 'aprobar_solicitud'),
    path(r'ver_solicitud/<int:pk>/', views.ver_solicitud, name = 'ver_solicitud'),
    path(r'solicitud_delete/<int:pk>/', views.SolicitudIngresoDelete.as_view(), name = 'solicitud_delete'),
]

matricula/models.py
from django.db import models
from usuarios.models import *
from institucion.models import *

# Create your models here.
class Matricula(models.Model):
    estudiante = models.ForeignKey(Estudiante, on_delete=models.CASCADE, null=True)
    ciclo_lectivo = models.ForeignKey(CicloLectivo, on_delete=models.CASCADE, null=True)
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE, null=True)
    paralelo = models.ForeignKey(Paralelo, on_delete=models.CASCADE, null=True)
    observacion = models.TextField(blank=True, null=True, help_text='Observación sobre la matrícula')
    fecha = models.DateField(auto_now_add=True)
    matricula_aceptada = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Matricula"
        verbose_name_plural = "Matriculas"

    def __str__(self):
        return self.estudiante.usuario.nombres

class SolicitudIngreso(models.Model):
    TIPO_MATRICULA = [
    ('1', 'ORDINARIA'),
    ('2', 'EXTRAORDINARIA'),
    ]
    VIENE_OTRA_INSTITUCION = [
    ('1', 'SI'),
    ('2', 'NO'),
    ('3', 'PASE'),
    ]
    fecha = models.DateField(auto_now_add=True)
    representante = models.ForeignKey(Representante, on_delete=models.CASCADE, null=True)
    estudiante = models.ForeignKey(Estudiante, on_delete=models.CASCADE, null=True)
    ciclo_lectivo = models.ForeignKey(CicloLectivo, on_delete=models.CASCADE, null=True)
    paralelo = models.ForeignKey(Paralelo, on_delete=models.CASCADE, null=True)
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE, null=True)
    tipo_matricula = models.CharField(max_length = 50, choices = TIPO_MATRICULA, default='2')
    viene_otra_institucion = models.CharField(max_length = 50, choices = VIENE_OTRA_INSTITUCION, default='1')
    f_aceptacion = models.DateField(blank=True, null=True)
    aprobacion = models.BooleanField(default=False)
    rector = models.ForeignKey(User, on_delete=models.CASCADE, related_name='rector')

    class Meta:
        verbose_name = "SolicitudIngreso"
        verbose_name_plural = "SolicitudesIngresos"

    def __str__(self):
        return self.estudiante.usuario.nombres

matricula/views.py
from django.shortcuts import render, redirect
from .forms import *
from usuarios.models import *
from usuarios.views import get_user
from django.contrib import messages
from datetime import date
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.urls import reverse, reverse_lazy


# Create your views here.
def matricula_create(request):
    print(Matricula.objects.all())
    user = User.objects.get(username = request.user)
    try:
        estudiante = Estudiante.objects.get(user=user)
        hay_estudiante = True
    except Exception as e:
        hay_estudiante = False
    ciclo_actual = CicloLectivo.objects.get(ciclo_actual = True)
    paralelos = Paralelo.objects.all()
    form_matricula = MatriculaForm()
    if hay_estudiante == True:
        if request.method == 'POST':
            form_matricula = MatriculaForm(request.POST)
            if form_matricula.is_valid():
                matricula = form_matricula.save(commit=False)
                matricula.estudiante = estudiante
                matricula.ciclo_lectivo = ciclo_actual
                matricula.save()
                messages.info(request, "Tú solicitud de matrícula fue creada con éxito")
                messages.info(request, "Le recordamos que el paralelo seleccionado, no es definitivo y puede ser cambiado por la persona encargada de reubicar los alumnos de la manera más pertinente")
                return redirect('matricula:matricula_list')
            else:
                messages.error(request, institucion.errors)
                context = {
                    'form_matricula': form_matricula,
                    'paralelos': paralelos,
                }
        context = {
            'form_matricula': form_matricula,
            'paralelos': paralelos,
            'hay_estudiante': hay_estudiante,
        }
    else:
        context = {
            'hay_estudiante': hay_estudiante,
        }
    return render(request, 'matricula/matricula_form.html', context)

def matricula_edit(request, pk):
    matricula = Matricula.objects.get(pk=pk)
    form_matricula = MatriculaForm(instance = matricula)
    paralelos = Paralelo.objects.all()
    hay_estudiante = True
    es_secretaria = get_user(request)
    es_secretaria = es_secretaria.groups.first()
    rol = Group.objects.get(name = "Secretaria")
    if request.method == 'POST':
        form_matricula = MatriculaForm(request.POST, instance = matricula)
        if form_matricula.is_valid():
            form_matricula.save()
            messages.info(request, "La matricula se editó con éxito")
            if es_secretaria == rol:
                return redirect('matricula:matriculas_pendientes_list')
            else:
                return redirect('matricula:matricula_list')

        else:
            messages.error(request, matricula.errors)
            context = {
                'form_matricula': form_matricula,
            }
            return render(request, 'matricula/matricula_form.html', context)

    context = {
        'form_matricula': form_matricula,
        'hay_estudiante': hay_estudiante,
        'paralelos': paralelos,
    }
    return render(request, 'matricula/matricula_form.html', context)

class MatriculaList(ListView):
    model = Matricula
    def get_context_data(self):
        queryset = super(MatriculaList, self).get_queryset()
        user = User.objects.get(username = self.request.user)
        ciclo_lectivo = CicloLectivo.objects.get(ciclo_actual=True)
        try:
            estudiante = Estudiante.objects.get(user=user)
            matriculas = Matricula.objects.filter(estudiante = estudiante, ciclo_lectivo = ciclo_lectivo)
            print(matriculas)
            if matriculas.count() > 0:
                hay_matricula = True
            else:
                hay_matricula = False
        except Exception as e:
            hay_matricula = False
        context = {
            'hay_matricula': hay_matricula,
            'matriculas': matriculas,
        }
        return context

class MatriculaDetail(DetailView):
	model = Matricula

class MatriculaDelete(DeleteView):
    model = Matricula
    success_url = reverse_lazy('matricula:matriculas_pendientes_list')

def matriculas_pendientes_list(request):
    matriculas = Matricula.objects.filter(matricula_aceptada=False)
    context = {
        'matriculas': matriculas,
    }
    return render(request, 'matricula/matriculas_pendientes_list.html', context)

def matriculados_list(request):
    matriculas = Matricula.objects.filter(matricula_aceptada=True)
    context = {
        'matriculas': matriculas,
    }
    return render(request, 'matricula/matriculados_list.html', context)

def matricula_aprobacion(request, pk):
    matriculas = Matricula.objects.filter(matricula_aceptada=False)
    matricula = Matricula.objects.get(pk=pk)
    matricula.matricula_aceptada = True
    messages.info(request, "La matricula se aprobo con éxito")
    matricula.save()
    context = {
        'matriculas': matriculas,
    }
    return render(request, 'matricula/matriculas_pendientes_list.html', context)

def desaprobar_matricula(request, pk):
    matriculas = Matricula.objects.filter(matricula_aceptada=True)
    matricula = Matricula.objects.get(pk=pk)
    matricula.matricula_aceptada = False
    messages.info(request, "La matricula se desaprobo con éxito")
    matricula.save()
    context = {
        'matriculas': matriculas,
    }
    return render(request, 'matricula/matriculados_list.html', context)

def certificado_matricula(request, pk):
    matricula = Matricula.objects.get(pk=pk)
    context = {
        'matricula': matricula,
    }
    return render(request, 'matricula/certificado_matricula.html', context)

def form_estudiantes_filter(request):
    form_filter_estudiantes = EstudiantesFilterForm()
    if request.method == 'POST':
        ciclo = request.POST.get('ciclo_lectivo')
        curso = request.POST.get('curso')
        paralelo = request.POST.get('paralelo')

        matriculas = Matricula.objects.filter(matricula_aceptada=True).order_by('estudiante__usuario__apellidos')

        if request.POST.get('ciclo_lectivo'):
            matriculas = matriculas.filter(ciclo_lectivo_id = ciclo).order_by('estudiante__usuario__apellidos')
        if request.POST.get('curso'):
            matriculas = matriculas.filter(curso_id = curso).order_by('estudiante__usuario__apellidos')
        if request.POST.get('paralelo'):
            matriculas = matriculas.filter(paralelo_id = paralelo).order_by('estudiante__usuario__apellidos')

        estudiante = matriculas.first()
        context = {
            'result_estudiantes_filter': matriculas,
            'estudiante': estudiante,
        }
        return render(request, 'matricula/list_estudiantes_filter.html', context)
    context = {
        'form_filter_estudiantes': form_filter_estudiantes,
    }
    return render(request, 'matricula/form_filter_estudiantes.html', context)


def solicitud_ingreso(request):

    return render(request, 'matricula/solicitud_ingreso.html')

def solicitud_ingreso_create(request):
    form_solicitud_ingreso = SolicitudIngresoForm(request)
    user = get_user(request)
    representante = Representante.objects.get(user = user)
    rector = User.objects.get(groups__name = 'Rector')
    print(rector)
    if request.method == 'POST':
        form_solicitud_ingreso = SolicitudIngresoForm(request, request.POST)
        if form_solicitud_ingreso.is_valid():
            solicitud = form_solicitud_ingreso.save(commit = False)
            solicitud.representante = representante
            solicitud.rector = rector
            solicitud.save()
            messages.info(request, "La solicitud se envio con éxito")
            return redirect('matricula:solicitud_ingreso_list')
    context = {
        'form_solicitud_ingreso': form_solicitud_ingreso,
    }
    return render(request, 'matricula/solicitud_form.html', context)

def solicitud_ingreso_list(request):
    user = get_user(request)
    representante = Representante.objects.get(user = user)
    solicitudes = SolicitudIngreso.objects.filter(representante=representante)
    context = {
        'solicitudes':solicitudes
    }
    return render(request, 'matricula/solicitudes_list.html', context)

def solicitudes_pendientes_list(request):
    solicitudes = SolicitudIngreso.objects.filter(aprobacion = False)
    context = {
        'solicitudes':solicitudes
    }
    return render(request, 'matricula/solicitudes_pendientes_list.html', context)

def solicitudes_aprobadas_list(request):
    solicitudes = SolicitudIngreso.objects.filter(aprobacion = True)
    context = {
        'solicitudes':solicitudes
    }
    return render(request, 'matricula/solicitudes_pendientes_list.html', context)

def aprobar_solicitud(request, pk):
    solicitud = SolicitudIngreso.objects.get(pk=pk)
    solicitud.aprobacion = True
    solicitud.f_aceptacion = date.today()
    solicitud.save()
    messages.info(request, "La solicitud se aprobo con éxito")
    return redirect('matricula:solicitudes_pendientes_list')

def ver_solicitud(request, pk):
    solicitud = SolicitudIngreso.objects.get(pk=pk)
    context = {
        'solicitud':solicitud
    }
    return render(request, 'matricula/solicitud_ingreso.html', context)

class SolicitudIngresoDelete(DeleteView):
    model = SolicitudIngreso
    success_url = reverse_lazy('matricula:solicitudes_pendientes_list')

templates/matricula/matricula_list.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
<div class="right_col" role="main">
  <div id="bootstrap_messages" style="margin-top:5em;">
    {% bootstrap_messages %}
  </div>
  <div class="">
      <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
          <div class="x_title">
            <h3>Mi Matricula</h3>
          </div>
          {% if hay_matricula == False %}
            <a href="{% url 'matricula:matricula_create' %}" type='GET'>
              <span class="btn btn-success btn-xs glyphicon glyphicon-plus" aria-hidden="true" title="matriculate"> Generar Matricula</span>
            </a>
          {% endif %}
          <div class="x_content">
            <div class="clearfix"></div>

              <div class="row">
                  <div class="col-sm-12">
                    <div class="card-box table-responsive">
            <table id="datatable" class="table table-striped table-bordered" style="width:100%">
              <thead>
                <tr>
                  <th>Id</th>
                  <th>Estudiante</th>
                  <th>Año lectivo </th>
                  <th>Curso</th>
                  <th>Paralelo</th>
                  <th>Observación</th>
                  <th>Fecha de solicitud</th>
                  <th>Certificado de Matricula</th>
                  <th>Acciones</th>
                </tr>
              </thead>


              <tbody>
                  {% for matricula in matriculas %}
                  <tr>
                    <td>{{ matricula.id }} </td>
                    <td>{{ matricula.estudiante }} </td>
                    <td>{{ matricula.ciclo_lectivo }} </td>
                    <td>{{ matricula.curso }} </td>
                    <td>{{ matricula.paralelo.nombre }} </td>
                    <td>{{ matricula.observacion }} </td>
                    <td>{{ matricula.fecha }} </td>
                    <td>
                      {% if matricula.matricula_aceptada == True %}
                      <a href="{% url 'matricula:certificado_matricula' matricula.pk %}" type='GET'>
    											<span class="btn btn-primary btn-xs glyphicon glyphicon-list-alt" aria-hidden="true" title="Certificado de matrícula"></span>
    										</a>
                        {% else %}
                        Su matrícula aun no es aceptada.
                        {% endif %}
                      </td>
                      <td>
                      <a href="{% url 'matricula:matricula_detail' matricula.pk %}" type='GET'>
    											<span class="btn btn-success btn-xs glyphicon glyphicon-eye-open" aria-hidden="true" title="Ver"></span>
    										</a>
                      <a href="{% url 'matricula:matricula_edit' matricula.pk %}" type='GET'>
    											<span class="btn btn-primary btn-xs glyphicon glyphicon-edit" aria-hidden="true" title="Editar"></span>
    										</a>

                    </td>
                  </tr>
                  {% endfor %}
              </tbody>
            </table>
          </div>
          </div>
      </div>
      </div>
        </div>
      </div>
    </div>
  </div>
</div>
      {% endblock content %}

templates/matricula/matriculados_list.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
<div class="right_col" role="main">
  <div id="bootstrap_messages" style="margin-top:5em;">
    {% bootstrap_messages %}
  </div>
  <div class="">
      <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
          <div class="x_title">
            <h3>Estudiantes Matriculados</h3>
          </div>
          <div class="x_content">
            <div class="clearfix"></div>

              <div class="row">
                  <div class="col-sm-12">
                    <div class="card-box table-responsive">
            <table id="datatable" class="table table-striped table-bordered" style="width:100%">
              <thead>
                <tr>
                  <th>Id</th>
                  <th>Estudiante</th>
                  <th>Año lectivo </th>
                  <th>Curso</th>
                  <th>Paralelo</th>
                  <th>Observación</th>
                  <th>Fecha de solicitud</th>
                  <th>Certificado de Matrícula</th>
                  <th>Acciones</th>
                </tr>
              </thead>


              <tbody>
                  {% for matricula in matriculas %}
                  <tr>
                    <td>{{ matricula.id }} </td>
                    <td>{{ matricula.estudiante }} </td>
                    <td>{{ matricula.ciclo_lectivo }} </td>
                    <td>{{ matricula.curso }} </td>
                    <td>{{ matricula.paralelo }} </td>
                    <td>{{ matricula.observacion }} </td>
                    <td>{{ matricula.fecha }} </td>
                    <td><a href="{% url 'matricula:certificado_matricula' matricula.pk %}" type='GET'>
                        <span class="btn btn-primary btn-xs glyphicon glyphicon-list-alt" aria-hidden="true" title="Certificado de matrícula"></span>
                      </a>
                    <td>
                      <a href="{% url 'matricula:matricula_detail' matricula.pk %}" type='GET'>
    											<span class="btn btn-success btn-xs glyphicon glyphicon-eye-open" aria-hidden="true" title="Ver"></span>
    										</a>
                      <a href="{% url 'matricula:matricula_edit' matricula.pk %}" type='GET'>
    											<span class="btn btn-primary btn-xs glyphicon glyphicon-edit" aria-hidden="true" title="Editar"></span>
    										</a>
                        <a href="{% url 'matricula:desaprobar_matricula' matricula.pk %}" type='GET'>
      											<span class="btn btn-danger btn-xs glyphicon glyphicon-ban-circle" aria-hidden="true" title="Quitar Matrícula"></span>
      										</a>
                    </td>
                  </tr>
                  {% endfor %}
              </tbody>
            </table>
          </div>
          </div>
      </div>
      </div>
        </div>
      </div>
    </div>
  </div>
</div>
      {% endblock content %}

templates/matricula/matriculas_pendientes_list.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% load user_tags %}
{% block content %}
<div class="right_col" role="main">
  <div id="bootstrap_messages" style="margin-top:5em;">
    {% bootstrap_messages %}
  </div>
  <div class="">

      <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
          <div class="x_title">
            <h3>Matrículas Pendientes de aprobación</h3>
          </div>
          <div class="x_content">
            <div class="clearfix"></div>

              <div class="row">
                  <div class="col-sm-12">
                    <div class="card-box table-responsive">
            <table id="datatable" class="table table-striped table-bordered" style="width:100%">
              <thead>
                <tr>
                  <th>Id</th>
                  <th>Cédula</th>
                  <th>Estudiante</th>
                  <th>Año lectivo </th>
                  <th>Curso</th>
                  <th>Paralelo</th>
                  <th>Observación</th>
                  <th>Fecha de solicitud</th>
                  <th>Aprobar matricula</th>
                  <th>Acciones</th>
                </tr>
              </thead>


              <tbody>
                  {% for matricula in matriculas %}
                  <tr>
                    <td>{{ matricula.id }} </td>
                    <td>{{ matricula.estudiante.usuario.ci_ruc }}</td>
                    <td>{{ matricula.estudiante.usuario.apellidos }} {{ matricula.estudiante.usuario.nombres }} </td>
                    <td>{{ matricula.ciclo_lectivo }} </td>
                    <td>{{ matricula.curso }} </td>
                    <td>{{ matricula.paralelo.nombre }} </td>
                    <td>{{ matricula.observacion }} </td>
                    <td>{{ matricula.fecha }} </td>
                    {% if user|has_group:"Secretaria" %}
                    <td><a href="{% url 'matricula:matricula_aprobacion' matricula.pk %}" type='GET'>
                        <span class="btn btn-success btn-xs glyphicon glyphicon-ok" aria-hidden="true" title="Aprobar Matrícula"></span>
                      </a>
                    </td>
                    {% else %}
                    <td>
                      <p>Usted no tiene el rol para aprobar matriculas</p>
                    </td>
                    {% endif %}
                    <td>
                      <a href="{% url 'matricula:matricula_detail' matricula.pk %}" type='GET'>
    											<span class="btn btn-success btn-xs glyphicon glyphicon-eye-open" aria-hidden="true" title="Ver"></span>
    										</a>
                      <a href="{% url 'matricula:matricula_edit' matricula.pk %}" type='GET'>
    											<span class="btn btn-primary btn-xs glyphicon glyphicon-edit" aria-hidden="true" title="Editar"></span>
    										</a>
                      {% if user|has_group:"Secretaria" %}
                      <a href="{% url 'matricula:matricula_delete' matricula.pk %}"  type='GET'>
    											<span class="btn btn-danger btn-xs glyphicon glyphicon-remove" aria-hidden="true" title="Eliminar"></span>
    										</a>
                      {% endif %}
                    </td>
                  </tr>
                  {% endfor %}
              </tbody>
            </table>
          </div>
          </div>
      </div>
      </div>
        </div>
      </div>
    </div>
  </div>
</div>
      {% endblock content %}

templates/matricula/solicitudes_pendientes_list.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
<div class="right_col" role="main">
  <div id="bootstrap_messages" style="margin-top:5em;">
    {% bootstrap_messages %}
  </div>
  <div class="">

      <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
          <div class="x_title">
            <h3>Solicitudes de ingreso de sus representados.</h3>
          </div>
          <div class="x_content">
            <div class="clearfix"></div>

              <div class="row">
                  <div class="col-sm-12">
                    <div class="card-box table-responsive">
            <table id="datatable" class="table table-striped table-bordered" style="width:100%">
              <thead>
                <tr>
                  <th>Id</th>
                  <th>Representante</th>
                  <th>Estudiante</th>
                  <th>Año Lectivo</th>
                  <th>Curso</th>
                  <th>Paralelo</th>
                  <th>Tipo de matricula</th>
                  <th>Viene de otra institución</th>
                  <th>Acciones</th>
                </tr>
              </thead>
              <tbody>
                  {% for solicitud in solicitudes %}
                  <tr>
                    <td>{{ solicitud.id }} </td>
                    <td>{{ solicitud.representante }} </td>
                    <td>{{ solicitud.estudiante.usuario.apellidos }} {{ solicitud.estudiante.usuario.nombres }} </td>
                    <td>{{ solicitud.ciclo_lectivo }} </td>
                    <td>{{ solicitud.curso }} </td>
                    <td>{{ solicitud.paralelo.nombre }} </td>
                    <td>{{ solicitud.get_tipo_matricula_display }} </td>
                    <td>{{ solicitud.get_viene_otra_institucion_display }} </td>
                      <td>
                        {% if solicitud.aprobacion == False %}
                        <a href="{% url 'matricula:aprobar_solicitud' solicitud.pk %}" type='GET'>
                          <span class="btn btn-success btn-xs glyphicon glyphicon-check" aria-hidden="true" title="Aprobar solicitud"></span>
                        </a>
                        {% endif %}
                        <a href="{% url 'matricula:ver_solicitud' solicitud.pk %}" type='GET'>
                          <span class="btn btn-success btn-xs glyphicon glyphicon-eye-open" aria-hidden="true" title="Ver solicitud"></span>
                        </a>
                        <!-- <a href="{% url 'matricula:certificado_matricula' solicitud.pk %}" type='GET'>
                          <span class="btn btn-primary btn-xs glyphicon glyphicon-list-alt" aria-hidden="true" title="Editar Solicitud"></span>
                        </a>
                        -->
                        <a href="{% url 'matricula:solicitud_delete' solicitud.pk %}" type='GET'>
                          <span class="btn btn-danger btn-xs glyphicon glyphicon-remove" aria-hidden="true" title="Eliminar Solicitud"></span>
                        </a>
                      </td>
                  </tr>
                  {% endfor %}
              </tbody>
            </table>
          </div>
          </div>
      </div>
      </div>
        </div>
      </div>
    </div>
  </div>
</div>
      {% endblock content %}