SisteMatriculacion/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'home/', include(('home.urls', 'home'), namespace ='home')),
    path(r'usuarios/', include(('usuarios.urls', 'usuarios'), namespace ='usuarios')),
    path(r'institucion/', include(('institucion.urls', 'institucion'), namespace ='institucion')),
    path(r'matricula/', include(('matricula.urls', 'matricula'), namespace ='matricula')),
    path(r'', include('home.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from home import views
# from django.contrib.auth import logout



urlpatterns = [
    # The home page
    path(r'', views.login, name='login'),
    path(r'index', views.index, name='index'),
    path(r'login', views.login, name='login'),
    url(r'logout', views.logout_view, name='logout'),
    # path(r'catalogo', views.catalogo, name='catalogo'),
    # path(r'nosotros', views.nosotros, name='nosotros'),
    # path(r'contacto', views.contacto, name='contacto'),
]

institucion/urls.py
from django.urls import path, include
from django.conf.urls import url
from institucion import views
# from django.contrib.auth import logout



urlpatterns = [
    # institucion
    path(r'institucion_create', views.institucion_create, name='institucion_create'),
    path(r'institucion_edit/<int:pk>/', views.institucion_edit, name='institucion_edit'),
    path(r'institucion_detail/<int:pk>/', views.InstitucionDetail.as_view(), name = 'institucion_detail'),
	path(r'institucion_list/', views.InstitucionList.as_view(), name = 'institucion_list'),
    # Ciclo
    path(r'ciclo_create', views.ciclo_create, name='ciclo_create'),
    path(r'ciclo_edit/<int:pk>/', views.ciclo_edit, name='ciclo_edit'),
    path(r'ciclo_detail/<int:pk>/', views.CicloDetail.as_view(), name = 'ciclo_detail'),
	path(r'ciclo_list/', views.CicloList.as_view(), name = 'ciclo_list'),
	path(r'ciclo_delete/<int:pk>/delete/', views.CicloDelete.as_view(), name='ciclo_delete'),
    # Curso
    path(r'curso_create', views.curso_create, name='curso_create'),
    path(r'curso_edit/<int:pk>/', views.curso_edit, name='curso_edit'),
    path(r'curso_detail/<int:pk>/', views.CursoDetail.as_view(), name = 'curso_detail'),
	path(r'curso_list/', views.CursoList.as_view(), name = 'curso_list'),
	path(r'curso_delete/<int:pk>/delete/', views.CursoDelete.as_view(), name='curso_delete'),

    # Paralelos
    path(r'paralelo_create', views.paralelo_create, name='paralelo_create'),
    path(r'paralelo_edit/<int:pk>/', views.paralelo_edit, name='paralelo_edit'),
    path(r'paralelo_detail/<int:pk>/', views.ParaleloDetail.as_view(), name = 'paralelo_detail'),
	path(r'paralelo_list/', views.ParaleloList.as_view(), name = 'paralelo_list'),
	path(r'paralelo_delete/<int:pk>/delete/', views.ParaleloDelete.as_view(), name='paralelo_delete'),

    # Preguntas PreguntasFrecuentes
    path(r'pregunta_create', views.pregunta_create, name='pregunta_create'),
    path(r'pregunta_edit/<int:pk>/', views.pregunta_edit, name='pregunta_edit'),
    path(r'pregunta_detail/<int:pk>/', views.PreguntaDetail.as_view(), name = 'pregunta_detail'),
	path(r'pregunta_list/', views.PreguntaList.as_view(), name = 'pregunta_list'),
	path(r'pregunta_delete/<int:pk>/delete/', views.PreguntaDelete.as_view(), name='pregunta_delete'),
]

institucion/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Institucion(models.Model):
	nombre = models.CharField(max_length=50, help_text='Nombre de su empresa.')
	slogan = models.TextField(blank=True, null=True, help_text='Frase Slogan de su negocio.')
	rector = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
	descripcion = models.TextField(blank=True, null=True, help_text='Describa el campo ocupacional y área de su empresa.')
	direccion = models.CharField(max_length=150, null=True)
	telefono = models.CharField(max_length=20, null=True)
	sitio_web = models.URLField(blank=True, null=True, help_text='Página web de su empresa.')

	class Meta:
		verbose_name = "Institucion"
		verbose_name_plural = "Instituciones"

	def __str__(self):
		return self.nombre


class CicloLectivo(models.Model):
	inicio = models.DateField(help_text='Inicio del año lectivo')
	fin = models.DateField(help_text='Fin del año lectivo')
	observacion= models.CharField(max_length=300, help_text='Observación sobre el año lectivo')
	ciclo_actual = models.BooleanField(default=True, help_text='Es el año lectivo actual con el que trabajará')


	class Meta:
		verbose_name = "Ciclo"
		verbose_name_plural = "Ciclos"

	def __str__(self):
		return self.observacion

class InstitucionCicloLectivo(models.Model):
	institucion = models.ForeignKey(Institucion, on_delete=models.CASCADE, null=True)
	ciclo_lectivo = models.ForeignKey(CicloLectivo, on_delete=models.CASCADE, null=True)

	class Meta:
		verbose_name = "InstitucionCicloLectivo"
		verbose_name_plural = "InstitucionesCiclosLectivos"

	def __str__(self):
		return self.institucion.nombre


class Curso(models.Model):
	nombre= models.CharField(max_length=300)
	ciclo_lectivo = models.ForeignKey(CicloLectivo, on_delete=models.CASCADE, null=True)

	class Meta:
		verbose_name = "Curso"
		verbose_name_plural = "Cursos"

	def __str__(self):
		return self.nombre


class Paralelo(models.Model):
	nombre= models.CharField(max_length=50)
	curso = models.ForeignKey(Curso, on_delete=models.CASCADE, null=True)

	class Meta:
		verbose_name = "Paralelo"
		verbose_name_plural = "Paralelos"

	def __str__(self):

		return "%s %s" %(self.nombre, self.curso.nombre)


class PreguntaFrecuente(models.Model):
	pregunta = models.CharField(max_length=500)
	respuesta = models.CharField(max_length=500)
	class Meta:
		verbose_name = "PreguntaFrecuente"
		verbose_name_plural = "PreguntasFrecuentes"

	def __str__(self):
		return self.pregunta

institucion/forms.py
from django import forms
from .models import *

class InstitucionForm(forms.ModelForm):
    class Meta:
        model = Institucion
        fields = '__all__'


class CicloForm(forms.ModelForm):
    class Meta:
        model = CicloLectivo
        fields = '__all__'
        widgets = {
			'inicio': forms.DateInput(attrs = {'type':'Date'}),
			'fin': forms.DateInput(attrs = {'type':'Date'}),
		}

class CursoForm(forms.ModelForm):
    class Meta:
        model = Curso
        fields = '__all__'

class ParaleloForm(forms.ModelForm):
    class Meta:
        model = Paralelo
        fields = (
        'curso',
        'nombre',
        )

class PreguntaFrecuenteForm(forms.ModelForm):
    class Meta:
        model = PreguntaFrecuente
        fields = '__all__'

institucion/views.py
from django.shortcuts import render, redirect
from institucion.forms import *
from institucion.models import *
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

# Create your views here.

def institucion_create(request):
    form_institucion = InstitucionForm()
    if request.method == 'POST':
        form_institucion = InstitucionForm(request.POST)
        if form_institucion.is_valid():
            form_institucion.save()
            return redirect('index')
    context = {
        'form_institucion': form_institucion,
    }
    return render(request, 'institucion/institucion_form.html', context)

def institucion_edit(request, pk):
    institucion = Institucion.objects.get(pk=pk)
    form_institucion = InstitucionForm(instance = institucion)
    if request.method == 'POST':
        form_institucion = InstitucionForm(request.POST, instance = institucion)
        if form_institucion.is_valid():
            form_institucion.save()
            messages.info(request, "La institución se editó con éxito")
            return redirect('institucion:institucion_list')
        else:
            messages.error(request, institucion.errors)
            context = {
                'form_institucion': form_institucion,
            }
            return render(request, 'institucion/institucion_form.html', context)

    context = {
        'form_institucion': form_institucion,
    }
    return render(request, 'institucion/institucion_form.html', context)

class InstitucionList(ListView):
	model = Institucion

class InstitucionDetail(DetailView):
	model = Institucion

def ciclo_create(request):
    form_ciclo = CicloForm()
    institucion = Institucion.objects.last()
    if request.method == 'POST':
        form_ciclo = CicloForm(request.POST)
        if form_ciclo.is_valid():
            #Todos los ciclos anteriores dejan de ser los actuales
            ciclos_anteriores = CicloLectivo.objects.all()
            for ciclo_anterior in ciclos_anteriores:
                ciclo_anterior.ciclo_actual = False
                ciclo_anterior.save()
            ciclo = form_ciclo.save()
            institucion_ciclo = InstitucionCicloLectivo.objects.create(institucion=institucion, ciclo_lectivo=ciclo)
            return redirect('institucion:ciclo_list')
    context = {
        'form_ciclo': form_ciclo,
    }
    return render(request, 'institucion/ciclo_form.html', context)

def ciclo_edit(request, pk):
    ciclo = CicloLectivo.objects.get(pk=pk)
    form_ciclo = CicloForm(instance = ciclo)
    if request.method == 'POST':
        form_ciclo = CicloForm(request.POST, instance = ciclo)
        if form_ciclo.is_valid():
            #Todos los ciclos anteriores dejan de ser los actuales
            ciclos_anteriores = CicloLectivo.objects.all()
            for ciclo_anterior in ciclos_anteriores:
                ciclo_anterior.ciclo_actual = False
                ciclo_anterior.save()
            form_ciclo.save()
            messages.info(request, "El ciclo se editó con éxito")
            return redirect('institucion:ciclo_list')
        else:
            messages.error(request, ciclo.errors)
            context = {
                'form_ciclo': form_ciclo,
            }
            return render(request, 'institucion/ciclo_form.html', context)

    context = {
        'form_ciclo': form_ciclo,
    }
    return render(request, 'institucion/ciclo_form.html', context)

class CicloList(ListView):
	model = CicloLectivo

class CicloDetail(DetailView):
	model = CicloLectivo

class CicloDelete(DeleteView):
    model = CicloLectivo
    success_url = reverse_lazy('institucion:ciclo_list')


def curso_create(request):
    form_curso = CursoForm()
    if request.method == 'POST':
        form_curso = CursoForm(request.POST)
        if form_curso.is_valid():
            form_curso.save()
            messages.info(request, "El curso se creo con éxito")
            return redirect('institucion:curso_list')
        else:
            messages.error(request, curso.errors)
            context = {
                'form_curso': form_curso,
            }
    context = {
        'form_curso': form_curso,
    }
    return render(request, 'institucion/curso_form.html', context)

def curso_edit(request, pk):
    curso = Curso.objects.get(pk=pk)
    form_curso = CursoForm(instance = curso)
    if request.method == 'POST':
        form_curso = CursoForm(request.POST, instance = curso)
        if form_curso.is_valid():
            form_curso.save()
            messages.info(request, "El curso se editó con éxito")
            return redirect('institucion:curso_list')
        else:
            messages.error(request, curso.errors)
            context = {
                'form_curso': form_curso,
            }
            return render(request, 'institucion/curso_form.html', context)

    context = {
        'form_curso': form_curso,
    }
    return render(request, 'institucion/curso_form.html', context)

class CursoList(ListView):
	model = Curso

class CursoDetail(DetailView):
	model = Curso

class CursoDelete(DeleteView):
    model = Curso
    success_url = reverse_lazy('institucion:curso_list')

def paralelo_create(request):
    form_paralelo = ParaleloForm()
    if request.method == 'POST':
        form_paralelo = ParaleloForm(request.POST)
        if form_paralelo.is_valid():
            form_paralelo.save()
            messages.info(request, 'El paralelo se creo con éxito.')
            return redirect('institucion:paralelo_list')
        else:
            messages.error(request, paralelo.errors)
            context = {
                'form_paralelo': form_paralelo,
            }
    context = {
        'form_paralelo': form_paralelo,
    }
    return render(request, 'institucion/paralelo_form.html', context)

def paralelo_edit(request, pk):
    paralelo = Paralelo.objects.get(pk=pk)
    form_paralelo = ParaleloForm(instance = paralelo)
    if request.method == 'POST':
        form_paralelo = ParaleloForm(request.POST, instance = paralelo)
        if form_paralelo.is_valid():
            form_paralelo.save()
            messages.info(request, "El paralelo se editó con éxito")
            return redirect('institucion:paralelo_list')
        else:
            messages.error(request, paralelo.errors)
            context = {
                'form_paralelo': form_paralelo,
            }
            return render(request, 'institucion/paralelo_form.html', context)

    context = {
        'form_paralelo': form_paralelo,
    }
    return render(request, 'institucion/paralelo_form.html', context)

class ParaleloList(ListView):
	model = Paralelo

class ParaleloDetail(DetailView):
	model = Paralelo

class ParaleloDelete(DeleteView):
    model = Paralelo
    success_url = reverse_lazy('institucion:paralelo_list')

def pregunta_create(request):
    form_pregunta = PreguntaFrecuenteForm()
    if request.method == 'POST':
        form_pregunta = PreguntaFrecuenteForm(request.POST)
        if form_pregunta.is_valid():
            form_pregunta.save()
            messages.info(request, 'La pregunta se creo con éxito.')
            return redirect('institucion:pregunta_list')
        else:
            messages.error(request, pregunta.errors)
            context = {
                'form_pregunta': form_pregunta,
            }
    context = {
        'form_pregunta': form_pregunta,
    }
    return render(request, 'institucion/preguntafrecuente_form.html', context)

def pregunta_edit(request, pk):
    pregunta = PreguntaFrecuente.objects.get(pk=pk)
    form_pregunta = PreguntaFrecuenteForm(instance = pregunta)
    if request.method == 'POST':
        form_pregunta = PreguntaFrecuenteForm(request.POST, instance = pregunta)
        if form_pregunta.is_valid():
            form_pregunta.save()
            messages.info(request, "La pregunta se editó con éxito")
            return redirect('institucion:pregunta_list')
        else:
            messages.error(request, pregunta.errors)
            context = {
                'form_pregunta': form_pregunta,
            }
            return render(request, 'institucion/preguntafrecuente_form.html', context)

    context = {
        'form_pregunta': form_pregunta,
    }
    return render(request, 'institucion/preguntafrecuente_form.html', context)


class PreguntaList(ListView):
	model = PreguntaFrecuente

class PreguntaDetail(DetailView):
	model = PreguntaFrecuente

class PreguntaDelete(DeleteView):
    model = PreguntaFrecuente
    success_url = reverse_lazy('institucion:pregunta_list')

templates/institucion/ciclolectivo_detail.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block content %}

<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Detalle del año lectivo</h3>
            </div>
        </div>
        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="x_panel">
                    <div class="x_content">

                          <h2>
                              <strong>Inicio:</strong>
                              <spam>{{object.inicio}}</spam>
                          </h2>
                          <h2>
                              <strong>Fin:</strong>
                              <span>{{ object.fin }}</span>
                          </h2>
                          <h2>
                              <strong>Observacion:</strong>
                              <span>{{ object.observacion }}</span>
                          </h2>
                          <h2>
                              <strong>Año Lectivo:</strong>
                              <span>{{ object.ciclo_actual }}</span>
                          </h2>
                          <div style="display: flex; justify-content: center;">
                              <a href="{% url 'institucion:ciclo_list' %}" class="btn btn-primary">Regresar</a>
                          </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/institucion/ciclolectivo_list.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
<div class="right_col" role="main">
  <div id="bootstrap_messages" style="margin-top:5em;">
    {% bootstrap_messages %}
  </div>
  <div class="">

      <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
          <div class="x_title">
            <h3>Lista de años lectivos</h3>
            <a href="{% url 'institucion:ciclo_create' %}" class="btn btn-success btn-sm">
              <span class="glyphicon glyphicon-plus"></span> Nuevo
            </a>

          </div>
          <div class="x_content">
            <div class="clearfix"></div>

              <div class="row">
                  <div class="col-sm-12">
                    <div class="card-box table-responsive">
            <table id="datatable" class="table table-striped table-bordered" style="width:100%">
              <thead>
                <tr>
                  <th>Id</th>
                  <th>Inicio</th>
                  <th>Fin</th>
                  <th>Observación</th>
                  <th>Activo</th>
                  <th>Acciones</th>
                </tr>
              </thead>


              <tbody>
                  {% for ciclo in object_list %}
                  <tr>
                    <td>{{ ciclo.id }} </td>
                    <td>{{ ciclo.inicio }} </td>
                    <td>{{ ciclo.fin }} </td>
                    <td>{{ ciclo.observacion }} </td>
                    <td>{{ ciclo.ciclo_actual }} </td>
                    <td>
                      <a href="{% url 'institucion:ciclo_detail' ciclo.pk %}" type='GET'>
    											<span class="btn btn-success btn-xs glyphicon glyphicon-eye-open" aria-hidden="true" title="Ver"></span>
    										</a>
                      <a href="{% url 'institucion:ciclo_edit' ciclo.pk %}" type='GET'>
    											<span class="btn btn-primary btn-xs glyphicon glyphicon-edit" aria-hidden="true" title="Editar"></span>
    										</a>
                      <a href="{% url 'institucion:ciclo_delete' ciclo.pk %}"  type='GET'>
    											<span class="btn btn-danger btn-xs glyphicon glyphicon-remove" aria-hidden="true" title="Eliminar"></span>
    										</a>
                    </td>
                  </tr>
                  {% endfor %}
              </tbody>
            </table>
          </div>
          </div>
      </div>
      </div>
        </div>
      </div>
    </div>
  </div>
</div>
      {% endblock content %}

templates/institucion/curso_detail.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block content %}

<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Detalle del Curso</h3>
            </div>
        </div>
        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="x_panel">
                    <div class="x_content">

                          <h2>
                              <strong>Nombre:</strong>
                              <spam>{{object.nombre}}</spam>
                          </h2>
                          <h2>
                              <strong>Curso:</strong>
                              <span>{{ object.ciclo_lectivo }}</span>
                          </h2>

                          <div style="display: flex; justify-content: center;">
                              <a href="{% url 'institucion:curso_list' %}" class="btn btn-primary">Regresar</a>
                          </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/institucion/curso_list.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
<div class="right_col" role="main">
  <div id="bootstrap_messages" style="margin-top:5em;">
    {% bootstrap_messages %}
  </div>
  <div class="">

      <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
          <div class="x_title">
            <h3>Lista de Cursos</h3>
            <a href="{% url 'institucion:curso_create' %}" class="btn btn-success btn-sm">
              <span class="glyphicon glyphicon-plus"></span> Nuevo
            </a>

          </div>
          <div class="x_content">
            <div class="clearfix"></div>

              <div class="row">
                  <div class="col-sm-12">
                    <div class="card-box table-responsive">
            <table id="datatable" class="table table-striped table-bordered" style="width:100%">
              <thead>
                <tr>
                  <th>Id</th>
                  <th>Nombre</th>
                  <th>Año Lectivo</th>
                  <th>Acciones</th>
                </tr>
              </thead>


              <tbody>
                  {% for curso in object_list %}
                  <tr>
                    <td>{{ curso.id }} </td>
                    <td>{{ curso.nombre }} </td>
                    <td>{{ curso.ciclo_lectivo }} </td>
                    <td>
                      <a href="{% url 'institucion:curso_detail' curso.pk %}" type='GET'>
    											<span class="btn btn-success btn-xs glyphicon glyphicon-eye-open" aria-hidden="true" title="Ver"></span>
    										</a>
                      <a href="{% url 'institucion:curso_edit' curso.pk %}" type='GET'>
    											<span class="btn btn-primary btn-xs glyphicon glyphicon-edit" aria-hidden="true" title="Editar"></span>
    										</a>
                      <a href="{% url 'institucion:curso_delete' curso.pk %}"  type='GET'>
    											<span class="btn btn-danger btn-xs glyphicon glyphicon-remove" aria-hidden="true" title="Eliminar"></span>
    										</a>
                    </td>
                  </tr>
                  {% endfor %}
              </tbody>
            </table>
          </div>
          </div>
      </div>
      </div>
        </div>
      </div>
    </div>
  </div>
</div>
      {% endblock content %}

templates/institucion/institucion_list.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
<div class="right_col" role="main">
  <div id="bootstrap_messages" style="margin-top:5em;">
    {% bootstrap_messages %}
  </div>
  <div class="">

      <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
          <div class="x_title">
            <h3>Institución</h3>
          </div>
          <div class="x_content">
            <div class="clearfix"></div>

              <div class="row">
                  <div class="col-sm-12">
                    <div class="card-box table-responsive">
            <table id="datatable" class="table table-striped table-bordered" style="width:100%">
              <thead>
                <tr>
                  <th>Id</th>
                  <th>Nombre</th>
                  <th>Slogan</th>
                  <th>Rector</th>
                  <th>Descripción</th>
                  <th>Dirección</th>
                  <th>Teléfono</th>
                  <th>Sitio Web</th>
                  <th>Acciones</th>
                </tr>
              </thead>


              <tbody>
                  {% for institucion in object_list %}
                  <tr>
                    <td>{{ institucion.id }} </td>
                    <td>{{ institucion.nombre }} </td>
                    <td>{{ institucion.slogan }} </td>
                    <td>{{ institucion.rector }} </td>
                    <td>{{ institucion.descripcion }} </td>
                    <td>{{ institucion.direccion }} </td>
                    <td>{{ institucion.telefono }} </td>
                    <td>{{ institucion.sitio_web }} </td>
                    <td>
                      <a href="{% url 'institucion:institucion_detail' institucion.pk %}" type='GET'>
    											<span class="btn btn-success btn-xs glyphicon glyphicon-eye-open" aria-hidden="true" title="Ver"></span>
    										</a>
                      <a href="{% url 'institucion:institucion_edit' institucion.pk %}" type='GET'>
    											<span class="btn btn-primary btn-xs glyphicon glyphicon-edit" aria-hidden="true" title="Editar"></span>
    										</a>
                    </td>
                  </tr>
                  {% endfor %}
              </tbody>
            </table>
          </div>
          </div>
      </div>
      </div>
        </div>
      </div>
    </div>
  </div>
</div>
      {% endblock content %}

templates/institucion/paralelo_list.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
<div class="right_col" role="main">
  <div id="bootstrap_messages" style="margin-top:5em;">
    {% bootstrap_messages %}
  </div>
  <div class="">
      <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
          <div class="x_title">
            <h3>Lista de Paralelos</h3>
            <a href="{% url 'institucion:paralelo_create' %}" class="btn btn-success btn-sm">
              <span class="glyphicon glyphicon-plus"></span> Nuevo
            </a>

          </div>
          <div class="x_content">
            <div class="clearfix"></div>

              <div class="row">
                  <div class="col-sm-12">
                    <div class="card-box table-responsive">
            <table id="datatable" class="table table-striped table-bordered" style="width:100%">
              <thead>
                <tr>
                  <th>Id</th>
                  <th>Curso</th>
                  <th>Nombre</th>
                  <th>Acciones</th>
                </tr>
              </thead>


              <tbody>
                  {% for paralelo in object_list %}
                  <tr>
                    <td>{{ paralelo.id }} </td>
                    <td>{{ paralelo.curso }} </td>
                    <td>{{ paralelo.nombre }} </td>
                    <td>
                      <a href="{% url 'institucion:paralelo_detail' paralelo.pk %}" type='GET'>
    											<span class="btn btn-success btn-xs glyphicon glyphicon-eye-open" aria-hidden="true" title="Ver"></span>
    										</a>
                      <a href="{% url 'institucion:paralelo_edit' paralelo.pk %}" type='GET'>
    											<span class="btn btn-primary btn-xs glyphicon glyphicon-edit" aria-hidden="true" title="Editar"></span>
    										</a>
                      <a href="{% url 'institucion:paralelo_delete' paralelo.pk %}"  type='GET'>
    											<span class="btn btn-danger btn-xs glyphicon glyphicon-remove" aria-hidden="true" title="Eliminar"></span>
    										</a>
                    </td>
                  </tr>
                  {% endfor %}
              </tbody>
            </table>
          </div>
          </div>
      </div>
      </div>
        </div>
      </div>
    </div>
  </div>
</div>
      {% endblock content %}

templates/institucion/preguntafrecuente_list.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
<div class="right_col" role="main">
  <div id="bootstrap_messages" style="margin-top:5em;">
    {% bootstrap_messages %}
  </div>
  <div class="">

      <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
          <div class="x_title">
            <h3>Lista de preguntas frecuentes</h3>
            <a href="{% url 'institucion:pregunta_create' %}" class="btn btn-success btn-sm">
              <span class="glyphicon glyphicon-plus"></span> Nuevo
            </a>

          </div>
          <div class="x_content">
            <div class="clearfix"></div>

              <div class="row">
                  <div class="col-sm-12">
                    <div class="card-box table-responsive">
            <table id="datatable" class="table table-striped table-bordered" style="width:100%">
              <thead>
                <tr>
                  <th>Id</th>
                  <th>Pregunta</th>
                  <th>Respuesta</th>
                  <th>Acciones</th>
                </tr>
              </thead>


              <tbody>
                  {% for pregunta in object_list %}
                  <tr>
                    <td>{{ pregunta.id }} </td>
                    <td>{{ pregunta.pregunta }} </td>
                    <td>{{ pregunta.respuesta }} </td>
                    <td>
                      <a href="{% url 'institucion:pregunta_detail' pregunta.pk %}" type='GET'>
    											<span class="btn btn-success btn-xs glyphicon glyphicon-eye-open" aria-hidden="true" title="Ver"></span>
    										</a>
                      <a href="{% url 'institucion:pregunta_edit' pregunta.pk %}" type='GET'>
    											<span class="btn btn-primary btn-xs glyphicon glyphicon-edit" aria-hidden="true" title="Editar"></span>
    										</a>
                      <a href="{% url 'institucion:pregunta_delete' pregunta.pk %}"  type='GET'>
    											<span class="btn btn-danger btn-xs glyphicon glyphicon-remove" aria-hidden="true" title="Eliminar"></span>
    										</a>
                    </td>
                  </tr>
                  {% endfor %}
              </tbody>
            </table>
          </div>
          </div>
      </div>
      </div>
        </div>
      </div>
    </div>
  </div>
</div>
      {% endblock content %}