SisteMatriculacion/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'home/', include(('home.urls', 'home'), namespace ='home')),
    path(r'usuarios/', include(('usuarios.urls', 'usuarios'), namespace ='usuarios')),
    path(r'institucion/', include(('institucion.urls', 'institucion'), namespace ='institucion')),
    path(r'matricula/', include(('matricula.urls', 'matricula'), namespace ='matricula')),
    path(r'', include('home.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from home import views
# from django.contrib.auth import logout



urlpatterns = [
    # The home page
    path(r'', views.login, name='login'),
    path(r'index', views.index, name='index'),
    path(r'login', views.login, name='login'),
    url(r'logout', views.logout_view, name='logout'),
    # path(r'catalogo', views.catalogo, name='catalogo'),
    # path(r'nosotros', views.nosotros, name='nosotros'),
    # path(r'contacto', views.contacto, name='contacto'),
]

usuarios/urls.py
from django.urls import path, include
from django.conf.urls import url
from usuarios import views
# from django.contrib.auth import logout



urlpatterns = [
#Datos del estudiante
    path(r'mis_datos', views.mis_datos, name='mis_datos'),
    path(r'mis_datos_list', views.mis_datos_list, name='mis_datos_list'),
    path(r'mis_datos_detail/<int:pk>/', views.MisDatosDetail.as_view(), name = 'mis_datos_detail'),
    path(r'mis_datos_edit/<int:pk>/', views.mis_datos_edit, name = 'mis_datos_edit'),
	path(r'mis_datos_delete/<int:pk>/delete/', views.MisDatosDelete.as_view(), name='mis_datos_delete'),

    #Datos de la madre del estudiante
    path(r'datos_madre', views.datos_madre, name='datos_madre'),
    path(r'datos_madre_edit/<int:pk>/', views.datos_madre_edit, name='datos_madre_edit'),
    path(r'datos_padres_list', views.datos_padres_list, name='datos_padres_list'),
    path(r'datos_padres_detail/<int:pk>/', views.DatosPadresDetail.as_view(), name='datos_padres_detail'),
    path(r'datos_padres_delete/<int:pk>/', views.datos_padres_delete, name='datos_padres_delete'),
    path(r'confirm_detele_padres/<int:pk>/', views.confirm_detele_padres, name='confirm_detele_padres'),
    path(r'datos_padre', views.datos_padre, name='datos_padre'),
    path(r'datos_padre_edit/<int:pk>/', views.datos_padre_edit, name='datos_padre_edit'),
    path(r'datos_representante', views.datos_representante, name='datos_representante'),
    path(r'datos_representante_edit/<int:pk>/', views.datos_representante_edit, name='datos_representante_edit'),
]

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from django.db.models.signals import post_save
from django.dispatch import receiver
from institucion.models import Institucion, CicloLectivo



class Usuario(models.Model):
	ci_ruc = models.CharField(max_length= 13, help_text='Cedula o RUC')
	nombres = models.CharField(max_length=200)
	apellidos = models.CharField(max_length=200)
	direccion = models.CharField(max_length= 200, null=True, blank=True)
	telefono = models.CharField(max_length=20, null=True, blank=True)
	celular = models.CharField(max_length=20, null=True, blank=True)

	class Meta:
		verbose_name = "Usuario"
		verbose_name_plural = "Usuarios"

	def __str__(self):
		return "%s %s" %(self.nombres, self.apellidos)

class Estudiante(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='usuario')
    usuario = models.OneToOneField(Usuario, on_delete=models.CASCADE, related_name='usuario_estudiante')
    f_nacimiento = models.DateField(help_text='Fecha de nacimiento')
    lugar_nacimiento = models.CharField(max_length= 13, help_text='Sector/Canton/Provincia')
    institucion = models.ForeignKey(Institucion, blank=True, null=True, on_delete=models.CASCADE)
    img_perfil = models.ImageField(upload_to='static/images/users', help_text='Escoja una Imagen de perfil')

    class Meta:
        verbose_name = "Estudiante"
        verbose_name_plural = "Estudiantes"

    def __str__(self):
        return self.usuario.nombres


class UsuarioCicloLectivo(models.Model):
	estudiante = models.ForeignKey(Estudiante, on_delete=models.CASCADE, null=True)
	ciclo_lectivo = models.ForeignKey(CicloLectivo, on_delete=models.CASCADE, null=True)

	class Meta:
		verbose_name = "UsuarioCicloLectivo"
		verbose_name_plural = "UsuariosCicloLectivo"

	def __str__(self):
		return self.estudiante.nombre


class Parentesco(models.Model):
    parentesco =  models.CharField(max_length =100)
    class Meta:
    	verbose_name = "Parentesco"
    	verbose_name_plural = "Parentescos"

    def __str__(self):
    	return self.parentesco

class NivelEducativo(models.Model):
    nivel_educativo =  models.CharField(max_length =100)
    class Meta:
    	verbose_name = "NivelEducativo"
    	verbose_name_plural = "NivelesEducativos"

    def __str__(self):
    	return self.nivel_educativo

class Profesion(models.Model):
    profesion =  models.CharField(max_length =100)
    class Meta:
    	verbose_name = "Profesion"
    	verbose_name_plural = "Profesiones"

    def __str__(self):
    	return self.profesion



class Padres(models.Model):
    PADRES_FAMILIA = [
    ('M', 'Mamá'),
    ('P', 'Papá'),
    ]
    padres_estudiante = models.ForeignKey(Estudiante, on_delete=models.CASCADE, related_name= 'padres_estudiante')
    usuario = models.OneToOneField(Usuario, on_delete=models.CASCADE, related_name='datos_padre')
    padres_familia = models.CharField(max_length = 50, choices = PADRES_FAMILIA, default='P')
    is_representante = models.BooleanField(default=False, help_text='Es representante del estudiante')
    parentesco = models.ForeignKey(Parentesco, on_delete=models.CASCADE)
    nivel_educacion = models.ForeignKey(NivelEducativo, on_delete=models.CASCADE)
    profesion = models.ForeignKey(Profesion, on_delete=models.CASCADE)
    class Meta:
        verbose_name = "Padres"
        verbose_name_plural = "Padres"

        def __str__(self):
            return self.usuario.ci_ruc

class Representante(models.Model):
	representante = models.ForeignKey(Padres, on_delete=models.CASCADE, related_name = 'representante_padres')
	user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user')

	class Meta:
		verbose_name = "Representante"
		verbose_name_plural = "Representantes"

	def __str__(self):
	    return self.user.username

usuarios/forms.py
from django import forms
from .models import *
import datetime
from django.utils import timezone

class DateInput(forms.DateInput):
	input_type = 'date'
	# initial = timezone.now()
	initial = datetime.date.today()

class TimeInput(forms.TimeInput):
	input_type = 'time'
	initial = timezone.now()

class UsuarioForm(forms.ModelForm):
	class Meta:
		model = Usuario
		fields = '__all__'


class EstudianteForm(forms.ModelForm):
    class Meta:
        model = Estudiante
        fields = (
            'f_nacimiento',
            'lugar_nacimiento',
            'img_perfil',
        )
        exclude = ['user', 'usuario', 'institucion', 'rol']
        widgets = {
			'f_nacimiento': forms.DateInput(attrs = {'type':'Date'}),
		}
class PadresForm(forms.ModelForm):
	class Meta:
	    model = Padres
	    fields = (
			'is_representante',
			'nivel_educacion',
			'profesion',
		)

class RepresentanteForm(forms.ModelForm):
	class Meta:
	    model = Padres
	    fields = (
			'nivel_educacion',
			'profesion',
			'parentesco',
		)

usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.urls import reverse, reverse_lazy
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from usuarios.forms import *
from django.contrib import messages

def get_user(request):
    user = User.objects.get(username = request.user)
    return user
# Create your views here.
def mis_datos(request):
    form_usuario = UsuarioForm()
    form_estudiante = EstudianteForm()
    # usuario_actual = User.objects.get(username = request.user)
    # print(usuario_actual)
    if request.method == 'POST':
        form_usuario = UsuarioForm(request.POST)
        form_estudiante = EstudianteForm(request.POST, request.FILES)
        if form_usuario.is_valid() and form_estudiante.is_valid():
            usuario = form_usuario.save()
            estudiante = form_estudiante.save(commit=False)
            estudiante.user = User.objects.get(username = request.user)
            estudiante.usuario = usuario
            estudiante.institucion = Institucion.objects.all().first()
            estudiante.save()
            messages.info(request, "Los datos del estudiante se guardaron con éxito")
            return redirect('usuarios:mis_datos_list')

    context = {
        'form_usuario': form_usuario,
        'form_estudiante': form_estudiante,
    }
    return render(request, 'usuarios/mis_datos.html', context)

def mis_datos_list(request):
    user = get_user(request)
    mis_datos = Estudiante.objects.filter(user=user)
    hay_datos = mis_datos.count()
    context = {
        'mis_datos': mis_datos,
        'hay_datos': hay_datos,
    }
    return render(request, 'usuarios/mis_datos_list.html', context)

def mis_datos_edit(request, pk):
    estudiante = Estudiante.objects.get(pk = pk)
    usuario = Usuario.objects.get(ci_ruc = estudiante.usuario.ci_ruc)
    form_usuario = UsuarioForm(instance = usuario)
    form_estudiante = EstudianteForm(instance = estudiante)
    if request.method == 'POST':
        form_usuario = UsuarioForm(request.POST, instance = usuario)
        form_estudiante = EstudianteForm(request.POST, request.FILES, instance = estudiante)
        if form_usuario.is_valid() and form_estudiante.is_valid():
            usuario = form_usuario.save()
            estudiante = form_estudiante.save(commit=False)
            estudiante.user = User.objects.get(username = request.user)
            estudiante.usuario = usuario
            estudiante.institucion = Institucion.objects.all().first()
            estudiante.save()
            messages.info(request, "Los datos del estudiante se editaron con éxito")
            return redirect('usuarios:mis_datos_list')

    context = {
        'form_usuario': form_usuario,
        'form_estudiante': form_estudiante,
    }
    return render(request, 'usuarios/mis_datos.html', context)



class MisDatosDetail(DetailView):
	model = Estudiante
# falta template de este no se lo puso por seguridad.
class MisDatosDelete(DeleteView):
    model = Estudiante
    success_url = reverse_lazy('usuarios:mis_datos_list')


def datos_madre(request):
    form_usuario = UsuarioForm()
    form_madre = PadresForm()
    estudiante_user =  User.objects.get(username = request.user)
    try:
        estudiante = Estudiante.objects.get(user = estudiante_user)
        hay_estudiante = True
    except Exception as e:
        hay_estudiante = False
    if hay_estudiante == True:
        if request.method == 'POST':
            form_usuario = UsuarioForm(request.POST)
            form_madre = PadresForm(request.POST)
            if form_usuario.is_valid() and form_madre.is_valid():
                # try:
                #     usuario_existente = Usuario.objects.get(ci_ruc = form_usuario.ci_ruc)
                #     usuario_existe = True
                # except Exception as e:
                #     usuario_existe = False
                # if usuario_existe == True:
                #     usuario_existente.padres_estudiante.add(estudiante)
                #     messages.info(request, "Los datos de la madre del estudiante se guardaron con éxito......")
                # else:
                usuario = form_usuario.save()
                madre = form_madre.save(commit=False)
                madre.padres_estudiante = estudiante
                madre.usuario = usuario
                madre.padres_familia = 'M'
                madre.parentesco = Parentesco.objects.get(parentesco = 'Madre')
                madre.save()
                messages.info(request, "Los datos de la madre del estudiante se guardaron con éxito")
                return redirect('usuarios:datos_padres_list')
        context = {
            'form_madre': form_madre,
            'form_usuario': form_usuario,
            'hay_estudiante': hay_estudiante,
        }
    else:
        context = {
            'hay_estudiante': hay_estudiante,
        }
    return render(request, 'usuarios/madre_form.html', context)

def datos_madre_edit(request, pk):
    madre = Padres.objects.get(pk=pk)
    usuario_madre = Usuario.objects.get(ci_ruc = madre.usuario.ci_ruc)
    form_usuario = UsuarioForm(instance = usuario_madre)
    form_madre = PadresForm(instance= madre)
    hay_estudiante = True
    if request.method == 'POST':
        form_usuario = UsuarioForm(request.POST, instance=usuario_madre)
        form_madre = PadresForm(request.POST, instance=madre)
        if form_usuario.is_valid() and form_madre.is_valid():
            usuario = form_usuario.save()
            madre = form_madre.save()
            messages.info(request, "Los datos de la madre del estudiante se editaron con éxito")
            return redirect('usuarios:datos_padres_list')
    context = {
        'form_madre': form_madre,
        'form_usuario': form_usuario,
        'hay_estudiante': hay_estudiante,
    }

    return render(request, 'usuarios/madre_form.html', context)


def datos_padres_list(request):
    user_actual = get_user(request)
    group = Group.objects.get(name= "Representante")
    user = User.objects.filter(groups = group)
    try:
        estudiante = Estudiante.objects.get(user=user_actual)
        hay_estudiante = True
    except Exception as e:
        hay_estudiante = False
        estudiante = None

    parentesco = Parentesco.objects.get(parentesco='Madre')
    padres = Padres.objects.filter(padres_estudiante = estudiante)
    hay_user_representante = False
    for representante in padres:
        if representante.is_representante == True:
            try:
                representante = Representante.objects.get(representante=representante)
                hay_user_representante = True
            except Exception as e:
                hay_user_representante = False
    hay_datos_madre = padres.filter(padres_familia = 'M').count()
    hay_datos_padre = padres.filter(padres_familia = 'P').count()
    context = {
        'padres': padres,
        'hay_datos_madre': hay_datos_madre,
        'hay_datos_padre': hay_datos_padre,
        'hay_user_representante': hay_user_representante,
        'hay_estudiante': hay_estudiante,
    }
    return render(request, 'usuarios/datos_padres_list.html', context)

class DatosPadresDetail(DetailView):
	model = Padres

def datos_padres_delete(request, pk):
    context = {
        'pk': pk,
    }
    return render(request, 'usuarios/confirm_detele_padres.html', context)

def confirm_detele_padres(request, pk):
    padre = Padres.objects.get(pk=pk)
    usuario_padre = Usuario.objects.filter(ci_ruc = padre.usuario.ci_ruc).first()
    usuario_padre.delete()
    padre.delete()
    messages.info(request, "Los datos se eliminaron con éxito")
    return redirect('usuarios:datos_padres_list')
    return render(request, 'usuarios/datos_padres_list.html')

def datos_padre(request):
    form_usuario = UsuarioForm()
    form_padre = PadresForm()
    estudiante_user =  User.objects.get(username = request.user)
    try:
        estudiante = Estudiante.objects.get(user = estudiante_user)
        hay_estudiante = True
    except Exception as e:
        hay_estudiante = False
    if hay_estudiante == True:
        if request.method == 'POST':
            form_usuario = UsuarioForm(request.POST)
            form_padre = PadresForm(request.POST)
            if form_usuario.is_valid() and form_padre.is_valid():
                usuario = form_usuario.save()
                padre = form_padre.save(commit=False)
                padre.padres_estudiante = estudiante
                padre.usuario = usuario
                padre.parentesco = Parentesco.objects.get(parentesco = 'Padre')
                padre.save()
                print("si guardo datos de la padre")
                return redirect('usuarios:datos_padres_list')
        context = {
            'form_padre': form_padre,
            'form_usuario': form_usuario,
            'hay_estudiante': hay_estudiante
        }
    else:
        context = {
            'hay_estudiante': hay_estudiante
        }
    return render(request, 'usuarios/padre_form.html', context)

def datos_padre_edit(request, pk):
    padre = Padres.objects.get(pk=pk)
    usuario_padre = Usuario.objects.filter(ci_ruc = padre.usuario.ci_ruc).first()
    form_usuario = UsuarioForm(instance = usuario_padre)
    form_padre = PadresForm(instance= padre)
    hay_estudiante = True
    if request.method == 'POST':
        form_usuario = UsuarioForm(request.POST, instance=usuario_padre)
        form_padre = PadresForm(request.POST, instance=padre)
        if form_usuario.is_valid() and form_padre.is_valid():
            usuario = form_usuario.save()
            padre = form_padre.save()
            messages.info(request, "Los datos del padre del estudiante se editaron con éxito")

templates/usuarios/confirm_detele_padres.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
            <div class="right_col" role="main">
                <div class="">

                    <div class="clearfix"></div>

                    <div class="row">
                        <div class="col-md-12 col-sm-12">
                            <div class="x_panel">
                                <div class="x_content">
                                  <div class="app-body">
                                    <div class="row d-flex justify-content-center col-sm-12 col-xl-12" align="center">
                                      <div class="col-sm-8" >
                                        <div class="card">
                                          <div class="card-header">
                                            <strong>Advertencia !!!</strong></div>
                                          <div class="card-body">
                                           <form method="post" action="{% url 'usuarios:confirm_detele_padres' pk %}">{% csrf_token %}
                                    		    <p>¿Está seguro que desea eliminar los datos?</p>
                                    		    <div class="card-footer">
                                              <button class="btn btn-sm btn-success" type="submit">
                                                <i class="fa fa-dot-circle-o"></i>Si</button>
                                              <a class="btn btn-sm btn-danger"  href="{% url 'usuarios:datos_padres_list' %}">
                                                <i class="fa fa-ban"></i>No</a>
                                            </div>
                                      		</form>
                                          </div>
                                        </div>
                                      </div>
                                      <div class="space-100"></div>
                                    </div>
                                  </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

{% endblock content %}

templates/usuarios/datos_padres_list.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
<div class="right_col" role="main">
  <div id="bootstrap_messages" style="margin-top:5em;">
    {% bootstrap_messages %}
  </div>
      <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
          <div class="x_title">
            <h3>Datos de Padres</h3>
          </div>
          {% if hay_estudiante == True %}
          {% if hay_datos_padre <= 0  %}
            <a href="{% url 'usuarios:datos_padre' %}" type='GET'>
              <span class="btn btn-success btn-xs glyphicon glyphicon-pencil" aria-hidden="true" title="Ingresar datos del padre"> Datos Padre</span>
            </a>
          {% endif %}
          {% if hay_datos_madre <= 0  %}
            <a href="{% url 'usuarios:datos_madre' %}" type='GET'>
              <span class="btn btn-success btn-xs glyphicon glyphicon-pencil" aria-hidden="true" title="Ingresar datos de la madre"> Datos Madre</span>
            </a>
          {% endif %}
          {% if hay_user_representante == False %}
          <a href="{% url 'usuarios:datos_representante' %}" type='GET'>
            <span class="btn btn-success btn-xs glyphicon glyphicon-pencil" aria-hidden="true" title="Ingresar datos del representante"> Datos Representante</span>
          </a>
          {% endif %}
          <div class="x_content">
            <div class="clearfix"></div>

              <div class="row">
                  <div class="col-sm-12">
                    <div class="card-box table-responsive">
            <table id="datatable" class="table table-striped table-bordered" style="width:100%">
              <thead>
                <tr>
                  <th>Cédula</th>
                  <th>Nombres</th>
                  <th>Apellidos</th>
                  <th>Dirección</th>
                  <th>Teléfono</th>
                  <th>Celular</th>
                  <th>Es Representante</th>
                  <th>Parentesco</th>
                  <th>Nivel Educacion</th>
                  <th>Profesion</th>
                  <th>Acciones</th>
                </tr>
              </thead>


              <tbody>
                  {% for datos in padres %}
                  <tr>
                    <td>{{ datos.usuario.ci_ruc }} </td>
                    <td>{{ datos.usuario.nombres }} </td>
                    <td>{{ datos.usuario.apellidos }} </td>
                    <td>{{ datos.usuario.direccion  }} </td>
                    <td>{{ datos.usuario.telefono }} </td>
                    <td>{{ datos.usuario.celular }} </td>
                    <td>
    									{% if datos.is_representante %}<img src="/static/admin/img/icon-yes.svg" alt="Si">
    									 {% else %} <img src="/static/admin/img/icon-no.svg" alt="No"> {% endif %}</td>
                    <td>{{ datos.parentesco.parentesco }} </td>
                    <td>{{ datos.nivel_educacion }} </td>
                    <td>{{ datos.profesion }} </td>
                    {% if datos.parentesco.parentesco == "Padre" %}
                      <td>
                        <a href="{% url 'usuarios:datos_padres_detail' datos.pk %}" type='GET'>
      											<span class="btn btn-success btn-xs glyphicon glyphicon-eye-open" aria-hidden="true" title="Ver"></span>
      										</a>
                        <a href="{% url 'usuarios:datos_padre_edit' datos.pk %}" type='GET'>
      											<span class="btn btn-primary btn-xs glyphicon glyphicon-edit" aria-hidden="true" title="Editar"></span>
      										</a>
                          <a href="{% url 'usuarios:datos_padres_delete' datos.pk %}"  type='GET'>
        											<span class="btn btn-danger btn-xs glyphicon glyphicon-remove" aria-hidden="true" title="Eliminar"></span>
        										</a>
                      </td>
                    {% else %}
                    {% if datos.parentesco.parentesco == "Madre" %}
                      <td>
                        <a href="{% url 'usuarios:datos_padres_detail' datos.pk %}" type='GET'>
                            <span class="btn btn-success btn-xs glyphicon glyphicon-eye-open" aria-hidden="true" title="Ver"></span>
                          </a>
                        <a href="{% url 'usuarios:datos_madre_edit' datos.pk %}" type='GET'>
                            <span class="btn btn-primary btn-xs glyphicon glyphicon-edit" aria-hidden="true" title="Editar"></span>
                          </a>
                          <a href="{% url 'usuarios:datos_padres_delete' datos.pk %}"  type='GET'>
                            <span class="btn btn-danger btn-xs glyphicon glyphicon-remove" aria-hidden="true" title="Eliminar"></span>
                          </a>
                      </td>
                    {% else %}
                    <td>
                      <a href="{% url 'usuarios:datos_padres_detail' datos.pk %}" type='GET'>
                          <span class="btn btn-success btn-xs glyphicon glyphicon-eye-open" aria-hidden="true" title="Ver"></span>
                        </a>
                      <a href="{% url 'usuarios:datos_representante_edit' datos.pk %}" type='GET'>
                          <span class="btn btn-primary btn-xs glyphicon glyphicon-edit" aria-hidden="true" title="Editar"></span>
                        </a>
                        <a href="{% url 'usuarios:datos_padres_delete' datos.pk %}"  type='GET'>
      											<span class="btn btn-danger btn-xs glyphicon glyphicon-remove" aria-hidden="true" title="Eliminar"></span>
      										</a>
                    </td>
                    {% endif %}
                    {% endif %}
                  </tr>
                  {% endfor %}
              </tbody>
            </table>
          </div>
          </div>
      </div>
      </div>
      {% else %}
        <h2>Para acceder a este menu debes primero completar tus datos</h2>
      {% endif %}
        </div>
      </div>
    </div>
  </div>
      {% endblock content %}

templates/usuarios/madre_form.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
            <div class="right_col" role="main">
                <div class="">
                    <div class="page-title">
                        <div class="title_left">
                            <h3>Datos Madre</h3>
                        </div>
                    </div>
                    <div class="clearfix"></div>

                    <div class="row">
                        <div class="col-md-12 col-sm-12">
                            <div class="x_panel">
                                <div class="x_content">
                                  <form  method="POST"  enctype="multipart/form-data">
                                    <span class="section">Información de la Madre</span>
                                      {% csrf_token %}
                                      {% if hay_estudiante == True %}
                                        {% bootstrap_form form_usuario layout='horizontal' %}
                                        {% bootstrap_form form_madre layout='horizontal' %}
                                          <div class="ln_solid">
                                              <div class="form-group">
                                                  <div class="col-md-6 offset-md-3">
                                                      <button type='submit' class="btn btn-success">Guardar</button>
                                                      <a href="{% url 'usuarios:datos_padres_list' %}" class="btn btn-primary">Regresar</a>
                                                  </div>
                                              </div>
                                          </div>
                                          {% else %}
                                            <h2>Para acceder a este menu debes primero completar tus datos</h2>
                                          {% endif %}
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

{% endblock content %}

templates/usuarios/mis_datos_list.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
<div class="right_col" role="main">
  <div id="bootstrap_messages" style="margin-top:5em;">
    {% bootstrap_messages %}
  </div>
  <div class="">

      <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
          <div class="x_title">
            <h3>Mi Datos</h3>
          </div>
          {% if hay_datos <= 0  %}
            <a href="{% url 'usuarios:mis_datos' %}" type='GET'>
              <span class="btn btn-success btn-xs glyphicon glyphicon-plus" aria-hidden="true" title="matriculate">Ingresar Datos</span>
            </a>
          {% endif %}
          <div class="x_content">
            <div class="clearfix"></div>

              <div class="row">
                  <div class="col-sm-12">
                    <div class="card-box table-responsive">
            <table id="datatable" class="table table-striped table-bordered" style="width:100%">
              <thead>
                <tr>
                  <th>Cedula</th>
                  <th>Nombres</th>
                  <th>Apellidos</th>
                  <th>Dirección</th>
                  <th>Teléfono</th>
                  <th>Celular</th>
                  <th>F. nacimiento</th>
                  <th>Lugar de nacimiento</th>
                  <th>Foto</th>
                  <th>Acciones</th>
                </tr>
              </thead>


              <tbody>
                  {% for datos in mis_datos %}
                  <tr>
                    <td>{{ datos.usuario.ci_ruc }} </td>
                    <td>{{ datos.usuario.nombres }} </td>
                    <td>{{ datos.usuario.apellidos }} </td>
                    <td>{{ datos.usuario.direccion  }} </td>
                    <td>{{ datos.usuario.telefono }} </td>
                    <td>{{ datos.usuario.celular }} </td>
                    <td>{{ datos.f_nacimiento }} </td>
                    <td>{{ datos.lugar_nacimiento }} </td>
                    <td>
                      <div class="thumb">
                        <img src="{{ datos.img_perfil.url }}" width="75" height="85" alt="{{ datos.img_perfil }}"
                          style="border-radius: 1em !important;">
                      </div>
                    </td>
                    <td>
                      <a href="{% url 'usuarios:mis_datos_detail' datos.pk %}" type='GET'>
    											<span class="btn btn-success btn-xs glyphicon glyphicon-eye-open" aria-hidden="true" title="Ver"></span>
    										</a>
                      <a href="{% url 'usuarios:mis_datos_edit' datos.pk %}" type='GET'>
    											<span class="btn btn-primary btn-xs glyphicon glyphicon-edit" aria-hidden="true" title="Editar"></span>
    										</a>
                    </td>
                  </tr>
                  {% endfor %}
              </tbody>
            </table>
          </div>
          </div>
      </div>
      </div>
        </div>
      </div>
    </div>
  </div>
</div>
      {% endblock content %}