SisteMatriculacion/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'home/', include(('home.urls', 'home'), namespace ='home')),
    path(r'usuarios/', include(('usuarios.urls', 'usuarios'), namespace ='usuarios')),
    path(r'institucion/', include(('institucion.urls', 'institucion'), namespace ='institucion')),
    path(r'matricula/', include(('matricula.urls', 'matricula'), namespace ='matricula')),
    path(r'', include('home.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from home import views
# from django.contrib.auth import logout



urlpatterns = [
    # The home page
    path(r'', views.login, name='login'),
    path(r'index', views.index, name='index'),
    path(r'login', views.login, name='login'),
    url(r'logout', views.logout_view, name='logout'),
    # path(r'catalogo', views.catalogo, name='catalogo'),
    # path(r'nosotros', views.nosotros, name='nosotros'),
    # path(r'contacto', views.contacto, name='contacto'),
]

institucion/urls.py
from django.urls import path, include
from django.conf.urls import url
from institucion import views
# from django.contrib.auth import logout



urlpatterns = [
    # institucion
    path(r'institucion_create', views.institucion_create, name='institucion_create'),
    path(r'institucion_edit/<int:pk>/', views.institucion_edit, name='institucion_edit'),
    path(r'institucion_detail/<int:pk>/', views.InstitucionDetail.as_view(), name = 'institucion_detail'),
	path(r'institucion_list/', views.InstitucionList.as_view(), name = 'institucion_list'),
    # Ciclo
    path(r'ciclo_create', views.ciclo_create, name='ciclo_create'),
    path(r'ciclo_edit/<int:pk>/', views.ciclo_edit, name='ciclo_edit'),
    path(r'ciclo_detail/<int:pk>/', views.CicloDetail.as_view(), name = 'ciclo_detail'),
	path(r'ciclo_list/', views.CicloList.as_view(), name = 'ciclo_list'),
	path(r'ciclo_delete/<int:pk>/delete/', views.CicloDelete.as_view(), name='ciclo_delete'),
    # Curso
    path(r'curso_create', views.curso_create, name='curso_create'),
    path(r'curso_edit/<int:pk>/', views.curso_edit, name='curso_edit'),
    path(r'curso_detail/<int:pk>/', views.CursoDetail.as_view(), name = 'curso_detail'),
	path(r'curso_list/', views.CursoList.as_view(), name = 'curso_list'),
	path(r'curso_delete/<int:pk>/delete/', views.CursoDelete.as_view(), name='curso_delete'),

    # Paralelos
    path(r'paralelo_create', views.paralelo_create, name='paralelo_create'),
    path(r'paralelo_edit/<int:pk>/', views.paralelo_edit, name='paralelo_edit'),
    path(r'paralelo_detail/<int:pk>/', views.ParaleloDetail.as_view(), name = 'paralelo_detail'),
	path(r'paralelo_list/', views.ParaleloList.as_view(), name = 'paralelo_list'),
	path(r'paralelo_delete/<int:pk>/delete/', views.ParaleloDelete.as_view(), name='paralelo_delete'),

    # Preguntas PreguntasFrecuentes
    path(r'pregunta_create', views.pregunta_create, name='pregunta_create'),
    path(r'pregunta_edit/<int:pk>/', views.pregunta_edit, name='pregunta_edit'),
    path(r'pregunta_detail/<int:pk>/', views.PreguntaDetail.as_view(), name = 'pregunta_detail'),
	path(r'pregunta_list/', views.PreguntaList.as_view(), name = 'pregunta_list'),
	path(r'pregunta_delete/<int:pk>/delete/', views.PreguntaDelete.as_view(), name='pregunta_delete'),
]

matricula/urls.py
from django.urls import path, include
from django.conf.urls import url
from matricula import views
# from django.contrib.auth import logout



urlpatterns = [
    # Matricula_estudiante
    path(r'matricula_create', views.matricula_create, name='matricula_create'),
    path(r'matricula_edit/<int:pk>/', views.matricula_edit, name='matricula_edit'),
    path(r'matricula_detail/<int:pk>/', views.MatriculaDetail.as_view(), name = 'matricula_detail'),
    path(r'matricula_list/', views.MatriculaList.as_view(), name = 'matricula_list'),

    # Matricula secretaria
    path(r'matriculas_pendientes_list/', views.matriculas_pendientes_list, name = 'matriculas_pendientes_list'),
    path(r'matriculados_list/', views.matriculados_list, name = 'matriculados_list'),
    path(r'matricula_aprobacion/<int:pk>/', views.matricula_aprobacion, name = 'matricula_aprobacion'),
    path(r'desaprobar_matricula/<int:pk>/', views.desaprobar_matricula, name = 'desaprobar_matricula'),
    path(r'certificado_matricula/<int:pk>/', views.certificado_matricula, name = 'certificado_matricula'),
    path(r'matricula_delete/<int:pk>/', views.MatriculaDelete.as_view(), name = 'matricula_delete'),

    # Lista de Estudiantes
    path(r'form_estudiantes_filter/', views.form_estudiantes_filter, name = 'form_estudiantes_filter'),
    # Solicitud de ingreso
    path(r'solicitud_ingreso_create/', views.solicitud_ingreso_create, name = 'solicitud_ingreso_create'),
    path(r'solicitud_ingreso/', views.solicitud_ingreso, name = 'solicitud_ingreso'),
    path(r'solicitud_ingreso_list/', views.solicitud_ingreso_list, name = 'solicitud_ingreso_list'),
    path(r'solicitudes_pendientes_list/', views.solicitudes_pendientes_list, name = 'solicitudes_pendientes_list'),
    path(r'solicitudes_aprobadas_list/', views.solicitudes_aprobadas_list, name = 'solicitudes_aprobadas_list'),
    path(r'aprobar_solicitud/<int:pk>/', views.aprobar_solicitud, name = 'aprobar_solicitud'),
    path(r'ver_solicitud/<int:pk>/', views.ver_solicitud, name = 'ver_solicitud'),
    path(r'solicitud_delete/<int:pk>/', views.SolicitudIngresoDelete.as_view(), name = 'solicitud_delete'),
]

usuarios/urls.py
from django.urls import path, include
from django.conf.urls import url
from usuarios import views
# from django.contrib.auth import logout



urlpatterns = [
#Datos del estudiante
    path(r'mis_datos', views.mis_datos, name='mis_datos'),
    path(r'mis_datos_list', views.mis_datos_list, name='mis_datos_list'),
    path(r'mis_datos_detail/<int:pk>/', views.MisDatosDetail.as_view(), name = 'mis_datos_detail'),
    path(r'mis_datos_edit/<int:pk>/', views.mis_datos_edit, name = 'mis_datos_edit'),
	path(r'mis_datos_delete/<int:pk>/delete/', views.MisDatosDelete.as_view(), name='mis_datos_delete'),

    #Datos de la madre del estudiante
    path(r'datos_madre', views.datos_madre, name='datos_madre'),
    path(r'datos_madre_edit/<int:pk>/', views.datos_madre_edit, name='datos_madre_edit'),
    path(r'datos_padres_list', views.datos_padres_list, name='datos_padres_list'),
    path(r'datos_padres_detail/<int:pk>/', views.DatosPadresDetail.as_view(), name='datos_padres_detail'),
    path(r'datos_padres_delete/<int:pk>/', views.datos_padres_delete, name='datos_padres_delete'),
    path(r'confirm_detele_padres/<int:pk>/', views.confirm_detele_padres, name='confirm_detele_padres'),
    path(r'datos_padre', views.datos_padre, name='datos_padre'),
    path(r'datos_padre_edit/<int:pk>/', views.datos_padre_edit, name='datos_padre_edit'),
    path(r'datos_representante', views.datos_representante, name='datos_representante'),
    path(r'datos_representante_edit/<int:pk>/', views.datos_representante_edit, name='datos_representante_edit'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    {% load bootstrap4 %}
    {% load user_tags %}
    {% block head %}
<head>
    {% block meta %}
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% endblock meta %}
    <title>Sistema de MAtriculación</title>

    {% block stylesheets %}

      <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/ico" />

      <!-- Bootstrap -->
      <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
      <!-- Font Awesome -->
      <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
      <!-- NProgress -->
      <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">
      <!-- iCheck -->
      <link href="{% static 'vendors/iCheck/skins/flat/green.css' %}" rel="stylesheet">

      <!-- bootstrap-progressbar -->
      <link href="{% static 'vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet">
      <!-- JQVMap -->
      <link href="{% static 'vendors/jqvmap/dist/jqvmap.min.css' %}" rel="stylesheet"/>
      <!-- bootstrap-daterangepicker -->
      <link href="{% static 'vendors/bootstrap-daterangepicker/daterangepicker.css' %}" rel="stylesheet">

      <!-- Datatables -->

      <link href="{% static 'vendors/datatables.net-bs/css/dataTables.bootstrap.min.css' %}" rel="stylesheet">
      <link href="{% static 'vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css' %}" rel="stylesheet">
      <link href="{% static 'vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css' %}" rel="stylesheet">
      <link href="{% static 'vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css' %}" rel="stylesheet">
      <link href="{% static 'vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css' %}" rel="stylesheet">
      <!-- Custom Theme Style -->
      <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">
    {% endblock stylesheets %}
</head>
{% endblock head %}
<body  class="nav-md">

  {% block body %}

  {% block menu %}
  <div class="container body">
    <div class="main_container">
      <div class="col-md-3 left_col">
        <div class="left_col scroll-view">
          <div class="navbar nav_title" style="border: 0;">
            <a href="{% url 'index' %}" class="site_title"><i class="fa fa-university"></i> Juan Bautista</a>
          </div>

          <div class="clearfix"></div>

          <!-- menu profile quick info -->
          <div class="profile clearfix">
            <div class="profile_pic">

              <img src="{% static 'images/logo_sanjuanbautista.jpeg' %}" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
              <span>Bienvenido:</span>
              <h2>{{ user }}</h2>
              <h2>{{ user|get_rol }}</h2>

            </div>
          </div>
          <!-- /menu profile quick info -->

          <br />

          <!-- sidebar menu -->
          <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
              <ul class="nav side-menu">
                {% if user|has_group:"Secretaria" or user|has_group:"SuperAdmin" %}
              <h3>Secretaría</h3>
              <li><a><i class="fa fa-newspaper-o"></i> Matriculas <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                  <li><a href="{% url 'matricula:matriculas_pendientes_list' %}">Matriculas pendientes</a></li>
                  <li><a href="{% url 'matricula:solicitudes_pendientes_list' %}">Solicitudes de Ingreso</a></li>
                  <li><a href="{% url 'matricula:matriculados_list' %}">Matriculados</a></li>
                  <li><a href="{% url 'matricula:solicitudes_aprobadas_list' %}">Solicitudes aprobadas</a></li>
                  <li><a href="{% url 'matricula:form_estudiantes_filter' %}">Lista de estudiantes</a></li>
                </ul>
              </li>
              <li><a><i class="fa fa-building-o"></i>Institución <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                  <li><a href="{% url 'institucion:ciclo_list' %}">Años Lectivos</a></li>
                  <li><a href="{% url 'institucion:curso_list' %}">Cursos</a></li>
                  <li><a href="{% url 'institucion:paralelo_list' %}">Paralelos</a></li>
                  <li><a href="{% url 'institucion:institucion_list' %}">Institución</a></li>
                  <li><a href="{% url 'institucion:pregunta_list' %}">Preguntas frecuentes</a></li>
                </ul>
              </li>
              {% endif %}
              {% if user|has_group:"Estudiante" or user|has_group:"SuperAdmin"%}
              <h3>Estudiante</h3>
              <li><a><i class="fa fa-folder-open-o"></i> Matrículas <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                  <li><a href="{% url 'usuarios:mis_datos_list' %}">Mis datos</a></li>
                  <li><a href="{% url 'usuarios:datos_padres_list' %}">Datos Generales</a></li>
                  <li><a href="{% url 'matricula:matricula_list' %}">Mi Matrícula</a></li>
                </ul>
              </li>
              {% endif %}
              {% if user|has_group:"Representante" or user|has_group:"SuperAdmin"%}
              <h3>Representante</h3>
              <li><a><i class="fa fa-folder-open-o"></i> Solicitudes <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                  <li><a href="{% url 'matricula:solicitud_ingreso_create' %}">Solicitud de ingreso</a></li>
                  <li><a href="{% url 'matricula:solicitud_ingreso_list' %}">Lista de solicitudes</a></li>
                </ul>
              </li>
              {% endif %}
              </ul>
            </div>

          </div>
          <!-- /sidebar menu -->
        </div>
      </div>
  {% endblock menu %}
  {% block navidator %}
  <!-- top navigation -->
  <div class="top_nav">
    <div class="nav_menu">
        <div class="nav toggle">
          <a id="menu_toggle"><i class="fa fa-bars"></i></a>
        </div>
        <nav class="nav navbar-nav">
        <ul class=" navbar-right">
          <li class="nav-item dropdown open" style="padding-left: 15px;">
              <a class="dropdown-item"  href="{% url 'logout' %}"><i class="fa fa-sign-out user-profile"></i>Cerrar Sesion</a>
          </li>
        </ul>
      </nav>
    </div>
  </div>
  <!-- /top navigation -->
  {% endblock navidator %}

        {% block content %}

        {% endblock content %}
        </main>
        {% block footer %}

        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Sistema de Matriculacion - Desarrollador por Mayra Ortega
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
        {% endblock footer %}

    {% endblock body %}



</body>
    {% block javascripts %}

        <!-- jQuery -->
        <script src="{% static 'vendors/jquery/dist/jquery.min.js' %}"></script>
        <!-- Bootstrap -->
        <script src="{% static 'vendors/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
        <!-- FastClick -->
        <script src="{% static 'vendors/fastclick/lib/fastclick.js' %}"></script>
        <!-- NProgress -->
        <script src="{% static 'vendors/nprogress/nprogress.js' %}"></script>
        <!-- Chart.js -->
        <script src="{% static 'vendors/Chart.js/dist/Chart.min.js' %}"></script>
        <!-- gauge.js -->
        <script src="{% static 'vendors/gauge.js/dist/gauge.min.js' %}"></script>
        <!-- bootstrap-progressbar -->
        <script src="{% static 'vendors/bootstrap-progressbar/bootstrap-progressbar.min.js' %}"></script>
        <!-- iCheck -->
        <script src="{% static 'vendors/iCheck/icheck.min.js' %}"></script>
        <!-- Skycons -->
        <script src="{% static 'vendors/skycons/skycons.js' %}"></script>
        <!-- Flot -->
        <script src="{% static 'vendors/Flot/jquery.flot.js' %}"></script>
        <script src="{% static 'vendors/Flot/jquery.flot.pie.js' %}"></script>
        <script src="{% static 'vendors/Flot/jquery.flot.time.js' %}"></script>
        <script src="{% static 'vendors/Flot/jquery.flot.stack.js' %}"></script>
        <script src="{% static 'vendors/Flot/jquery.flot.resize.js' %}"></script>
        <!-- Flot plugins -->
        <script src="{% static 'vendors/flot.orderbars/js/jquery.flot.orderBars.js' %}"></script>
        <script src="{% static 'vendors/flot-spline/js/jquery.flot.spline.min.js' %}"></script>
        <script src="{% static 'vendors/flot.curvedlines/curvedLines.js' %}"></script>
        <!-- DateJS -->
        <script src="{% static 'vendors/DateJS/build/date.js' %}"></script>
        <!-- JQVMap -->
        <script src="{% static 'vendors/jqvmap/dist/jquery.vmap.js' %}"></script>
        <script src="{% static 'vendors/jqvmap/dist/maps/jquery.vmap.world.js' %}"></script>
        <script src="{% static 'vendors/jqvmap/examples/js/jquery.vmap.sampledata.js' %}"></script>
        <!-- bootstrap-daterangepicker -->
        <script src="{% static 'vendors/moment/min/moment.min.js' %}"></script>
        <script src="{% static 'vendors/bootstrap-daterangepicker/daterangepicker.js' %}"></script>

        <!-- Datatables -->
        <script src="{% static 'vendors/datatables.net/js/jquery.dataTables.min.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-keytable/js/dataTables.keyTable.min.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-scroller/js/dataTables.scroller.min.js' %}"></script>
        <script src="{% static 'vendors/jszip/dist/jszip.min.js' %}"></script>
        <script src="{% static 'vendors/pdfmake/build/pdfmake.min.js' %}"></script>
        <script src="{% static 'vendors/pdfmake/build/vfs_fonts.js' %}"></script>

        <!-- Custom Theme Scripts -->
        <script src="{% static 'build/js/custom.min.js' %}"></script>
        <!-- jQuery Smart Wizard -->
    {% endblock javascripts %}
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
        <!-- page content -->
        <div class="right_col" role="main">
          <!-- top tiles -->
          <div class="row" style="display: inline-block;" >
          <div class="tile_count">
            {% if rol.name == "SuperAdmin" or rol.name == "Secretaria" %}
            <div class="col-md-2 col-sm-4  tile_stats_count">
              <span class="count_top"><i class="fa fa-user"></i> Total estudiantes</span>
              <div class="count green">{{estudiantes}}</div>
            </div>
            <div class="col-md-2 col-sm-4  tile_stats_count">
              <span class="count_top"><i class="fa fa-clock-o"></i> Matriculados</span>
              <div class="count green">{{matriculados}}</div>
            </div>
            <div class="col-md-2 col-sm-4  tile_stats_count">
              <span class="count_top"><i class="fa fa-user"></i> M. Pendientes</span>
              <div class="count red">{{matriculas_pendientes}}</div>
            </div>
            <div class="col-md-2 col-sm-4  tile_stats_count">
              <span class="count_top"><i class="fa fa-user"></i> Nro Cursos</span>
              <div class="count blue">{{cursos}}</div>
            </div>
            <div class="col-md-2 col-sm-4  tile_stats_count">
              <span class="count_top"><i class="fa fa-user"></i> Nro Paralelos</span>
              <div class="count blue">{{paralelos}}</div>
            </div>
            <div class="col-md-2 col-sm-4  tile_stats_count">
              <span class="count_top"><i class="fa fa-user"></i> Nro Usuarios</span>
              <div class="count blue">{{usuarios}}</div>
            </div>
            {% endif %}
            <div class="col-md-2 col-sm-4  tile_stats_count">
            </div>
          </div>
        </div>

          <!-- /top tiles -->

          <div class="row">
            <div class="col-md-12 col-sm-12 ">
              <div class="dashboard_graph">




                <div class="col-md-6 col-sm-6 ">
          <div class="row">



                <div class="x_content">

                  <div class="dashboard-widget-content">

                    <h3>Preguntas Frecuentes</h3>
                    <ul class="list-unstyled timeline widget">
                      {% for pregunta in preguntas %}
                      <li>
                        <div class="block">
                          <div class="block_content">
                            <h2 class="title">
                                <a style="text-align: justify">{{ pregunta.pregunta }}</a>
                            </h2>
                            <br/>
                            <p class="excerpt" style="text-align: justify">{{pregunta.respuesta}}</p>
                          </div>
                        </div>
                      </li>
                      {% endfor %}
                    </ul>
                  </div>
                </div>
                </div>
              </div>
              <div class="col-md-6 col-sm-6">
                <img src="{% static 'images/logo_sanjuanbautista.jpeg' %}" alt="..." class="img-circle profile_img">
              </div>
            </div>
          </div>
        </div>
      </div>
        <!-- /page content -->
        {% endblock content %}

templates/login.html
{% load static %}
{% load bootstrap4 %}
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Iniciar Sesión | </title>

    <!-- Bootstrap -->
    <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">
    <!-- Animate.css -->
    <link href="{% static 'vendors/animate.css/animate.min.css' %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">
  </head>

  <body class="login">
    <div>
      <a class="hiddenanchor" id="signup"></a>
      <a class="hiddenanchor" id="signin"></a>

      <div class="login_wrapper">

        <div class="animate form login_form">
          <div>
            <div class="col-md-12 col-sm-12">
              <img src="{% static 'images/logo_sanjuanbautista.jpeg' %}" alt="..." class="img-circle profile_img">
            </div>
            <div   align="center" class="col-md-12 col-sm-12">
              <strong><p>UNIDAD EDUCATIVA FISCOMISIONAL</p></strong>
            <strong><p>"SAN JUAN BAUTISTA"</p></strong>
          </div>
          </div>
          <section class="login_content">
            <form method="POST" enctype="multipart/form-data">
              <div   align="center" class="col-md-12 col-sm-12">
              <h1>Iniciar Sesión</h1>
            </div>
              {% csrf_token %}
              {% bootstrap_form form_login layout='inline' %}


                <button class="btn btn-sm btn-success" type="submit">
                  <i class="fa fa-dot-circle-o"></i>  Iniciar Sesion</button>
                <!-- <a class="reset_pass" href="#">Olvidaste tu contraseña</a> -->

              <div class="clearfix"></div>

              <div class="separator">
                <p class="change_link">No estas registrado?
                  <a href="#signup" class="to_register" id="link_register" onclick="is_register()"> Regístrate </a>
                </p>

                <div class="clearfix"></div>
                <br />

                <h1><i class="fa fa-university"></i>Sistema de Matrículas</h1>

              </div>
            </form>
          </section>
        </div>

        <div id="register" class="animate form registration_form">
          <div>
            <div class="col-md-12 col-sm-12">
              <img src="{% static 'images/logo_sanjuanbautista.jpeg' %}" alt="..." class="img-circle profile_img">
            </div>
            <div   align="center" class="col-md-12 col-sm-12">
              <strong><p>UNIDAD EDUCATIVA FISCOMISIONAL</p></strong>
            <strong><p>"SAN JUAN BAUTISTA"</p></strong>
          </div>
          </div>
          <section class="login_content">
            <form  method="POST" action="{% url 'login' %}" id="register" enctype="multipart/form-data">
              <div   align="center" class="col-md-12 col-sm-12">
              <h1>Regístrate</h1>
            </div>
                {% csrf_token %}
                {% bootstrap_form form_register layout='inline' %}
                <input type="hidden" name="is_register" value="" id="is_register" >
                <button class="btn btn-sm btn-success" type="submit">
                  <i class="fa fa-dot-circle-o"></i>Registrarse</button>

              <div class="clearfix"></div>

              <div class="separator">
                <p class="change_link">Ya estas registrado?
                  <a href="#signin" class="to_register" id="link_login" onclick="is_login()"> Iniciar sesión </a>
                </p>

                <div class="clearfix"></div>
                <br />

                <div>
                  <h1><i class="fa fa-university"></i>Sistema de Matrículas</h1>
                </div>
              </div>
            </form>
          </section>
        </div>
      </div>
    </div>
  </body>
  <script type="text/javascript" id="register">

  function is_register(){
    let register = document.getElementById('is_register')
    register.value = 'True'
    console.log(register)
  }
  function is_login(){
    let register = document.getElementById('is_register')
    register.value = 'False'
    console.log(register)
  }
</script>
</html>